spring.application.name=HackHub
spring.profiles.active=dev
spring.datasource.url=jdbc:h2:mem:hackhub
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL:false}
spring.jpa.open-in-view=false
spring.sql.init.mode=never
logging.level.org.springframework.security=${SPRING_SECURITY_LOG_LEVEL:INFO}
app.time.mode=fixed
app.time.fixed=2026-02-01T18:00:01
